name: android-build

on: workflow_dispatch

jobs:
  build-apk-for-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Android (32 bit)
      run: |
        scripts/build-android-armv7a.sh

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@main
      with:
        name: Android Files
        path: /home/runner/work/Hl2-mods-tests/Hl2-mods-tests/build
