name: Android Build

on: workflow_dispatch

jobs:
  build-android-armv7a:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
        
    - name: 'Upload All'
      uses: actions/upload-artifact@main
      with:
        name: Android All
        path: /home/runner/work/Hl2-mods-tests/Hl2-mods-tests/srceng-mod-launcher/build/
   
    - name: 'Upload Libs'
      uses: actions/upload-artifact@main
      with:
        name: Android libs
        path: /home/runner/work/Hl2-mods-tests/Hl2-mods-tests/srceng-mod-launcher/android/lib/
